-- Migration 039 — les tables de la CHAÎNE DE COLLECTE (chantier v3, lot 2c).
--
-- ADDITIVE : trois tables NEUVES, aucune donnée existante touchée, aucune colonne retirée.
-- Réversible par `DROP TABLE` (ordre inverse des FK). Rien du code déployé n'en dépend encore.
--
-- ORDRE DU CHANTIER — l'AGENT dicte la table, jamais l'inverse. Le contrat `collection_plan_schema`,
-- le pont `valider_pont_collection_plan` et l'aiguilleur `collecteur.aiguiller_plan` sont écrits et
-- éprouvés AVANT cette migration : ces colonnes sont la projection de leurs objets
-- (`CollectionPlan`/`Item`, `LienCouverture`, `MandatCollecte`), pas une conception de schéma.
--
-- LES CHECK REDISENT LE CONTRAT — non par redondance, mais parce qu'une contrainte de base est le
-- DERNIER rempart si une écriture contournait un jour le contrat Pydantic. Éprouvés en négatif par
-- `checks/check_collecte_persist.py` (une ligne `traduit` sans métrique, un mandat d'origine
-- inconnue : la base REFUSE).

BEGIN;

-- Le plan, DATÉ et VERSIONNÉ (§3.6). Grain logique (ticker, framework, version), mais PLUSIEURS
-- générations dans le temps — le corpus de RVMD ne vaut pas la même chose en janvier et après une
-- lecture clinique. D'où un id propre + `created_at`, JAMAIS une unicité sur le triple (qui
-- interdirait de re-planifier).
CREATE TABLE public.collection_plans (
    id                integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id         text        NOT NULL REFERENCES public.tickers(id),
    framework_id      text        NOT NULL,
    framework_version text        NOT NULL,
    archetype         text        NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_collection_plans_cle
    ON public.collection_plans (ticker_id, framework_id, framework_version);

-- Une ligne par ingrédient. Le CHECK REDIT `_le_statut_porte_exactement_sa_charge` du contrat :
-- `traduit` ⟺ métrique + source + ancre, motif NULL ; `inobtenable` ⟺ motif, les trois autres NULL.
-- `omis` n'est PAS un statut (c'est l'absence de ligne, vue au pont), donc absent du CHECK.
CREATE TABLE public.collection_plan_items (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id           integer NOT NULL REFERENCES public.collection_plans(id) ON DELETE CASCADE,
    question_id       text    NOT NULL,
    ingredient_id     text    NOT NULL,
    statut            text    NOT NULL,
    metrique          text,
    source_pressentie text,
    ancre             text,
    motif             text,
    CONSTRAINT collection_plan_items_unique UNIQUE (plan_id, question_id, ingredient_id),
    CONSTRAINT collection_plan_items_statut CHECK (statut IN ('traduit', 'inobtenable')),
    CONSTRAINT collection_plan_items_charge CHECK (
        (statut = 'traduit'
            AND metrique IS NOT NULL AND source_pressentie IS NOT NULL AND ancre IS NOT NULL
            AND motif IS NULL)
        OR
        (statut = 'inobtenable'
            AND motif IS NOT NULL
            AND metrique IS NULL AND source_pressentie IS NULL AND ancre IS NULL)
    )
);

-- Un MANDAT de recherche ouvert : un ingrédient qu'on n'a pas pu ranger, mais NOMMÉ (jamais un trou).
-- Deux origines aujourd'hui (le traducteur savait ⟶ `inobtenable` ; la collecte a échoué ⟶
-- `echec_collecte`) ; `manager_renvoi` est prévu pour le lot 4 (le renvoi du manager produit un
-- mandat). État de vie ouvert/servi/abandonne.
CREATE TABLE public.framework_mandates (
    id                integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    framework_id      text        NOT NULL,
    framework_version text        NOT NULL,
    question_id       text        NOT NULL,
    ingredient_id     text        NOT NULL,
    motif             text        NOT NULL,
    origine           text        NOT NULL,
    statut            text        NOT NULL DEFAULT 'ouvert',
    plan_id           integer     REFERENCES public.collection_plans(id) ON DELETE SET NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT framework_mandates_origine
        CHECK (origine IN ('inobtenable', 'echec_collecte', 'manager_renvoi')),
    CONSTRAINT framework_mandates_statut
        CHECK (statut IN ('ouvert', 'servi', 'abandonne'))
);
-- Un mandat OUVERT est ce qu'on rejoue ; l'index partiel sert cette lecture.
CREATE INDEX idx_framework_mandates_ouvert
    ON public.framework_mandates (framework_id, framework_version, question_id)
    WHERE statut = 'ouvert';

-- Le rôle applicatif lit et écrit ces tables. (La convention #15 — ALTER DEFAULT PRIVILEGES — couvre
-- déjà les tables créées par `admin` ; ce GRANT explicite est une ceinture par-dessus les bretelles.)
GRANT SELECT, INSERT, UPDATE, DELETE
    ON public.collection_plans, public.collection_plan_items, public.framework_mandates
    TO portfolio_user;

COMMIT;
