-- Migration 040 — les tables de la RÉPONSE et de la DISPENSE (chantier v3, lot 3, maillon 2).
--
-- ADDITIVE : deux tables NEUVES, aucune donnée existante touchée, aucune colonne retirée.
-- Réversible par `DROP TABLE` (ordre inverse des FK). Rien du code déployé n'en dépend encore.
--
-- ORDRE DU CHANTIER — l'AGENT dicte la table, jamais l'inverse. Le contrat
-- `contracts/framework_answer_schema.py` et le pont `valider_pont_framework_answer`
-- (`agents/v2/frameworks.py`) sont écrits et éprouvés AVANT cette migration : ces colonnes sont la
-- projection de `FrameworkAnswer`, pas une conception de schéma.
--
-- ⚠️ `framework_version` PARTOUT — sans elle, une réponse ou une dispense survit à la question
-- qu'elle décrivait (écart V10, §5.2). C'est exactement le défaut que la relecture de ce lot a
-- trouvé sur le contrat `FrameworkAnswer` lui-même (le champ manquait) avant d'écrire une ligne de
-- schéma : le contrat et le pont le portent depuis ce lot (invariant [V]), cette migration ne fait
-- que lui donner une colonne à écrire.
--
-- LES CHECK REDISENT LE CONTRAT — dernier rempart si une écriture contournait un jour le pont
-- Pydantic. Éprouvés en négatif par `checks/negatif_framework_persist.sh`.

BEGIN;

-- La réponse d'UN analyste à UNE question d'UN framework, pour UN émetteur (spec §2.4).
-- Append-only + versionnée (A1, comme `knowledge_entries`, migration 024) : une réponse corrigée ne
-- se met pas à jour, elle supersède. `superseded_by IS NULL` = la ligne courante d'une lignée
-- (ticker, framework, version, question, analyste) — deux analystes distincts (§3.4, N ≥ 1) ne se
-- supersèdent JAMAIS l'un l'autre, seule une correction du MÊME analyste ferme la ligne précédente.
--
-- Les colonnes `framework`, `rang_degrade`, `methode_approximation`, `ingredients`, `motif`
-- reprennent la nomenclature DEVINÉE par le test d'acceptation du lot 0
-- (`COLONNES_DENORMALISEES`, `contracts/framework_answer_schema.py`) : deux nomenclatures d'accord
-- restent deux nomenclatures (#46), donc la colonne porte le nom que le lecteur attend déjà, pas
-- celui du contrat. `framework_version` est un champ NEUF du contrat, absent de cette nomenclature
-- héritée : il porte son propre nom, canonique. `answer_json` porte le contrat COMPLET (`reponse`,
-- `fondation`, `approximation`, `sans_objet`, `gap`, `manager`) — les colonnes dénormalisées
-- n'existent que pour ce qu'un lecteur doit pouvoir lire sans reparser le JSON (T2-T5).
CREATE TABLE public.framework_answers (
    id                     integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    framework              text        NOT NULL,
    framework_version      text        NOT NULL,
    question_id            text        NOT NULL,
    ticker_id              text        NOT NULL REFERENCES public.tickers(id),
    analyste               text        NOT NULL,
    statut                 text        NOT NULL,
    answer_json            jsonb       NOT NULL,
    cited_entry_ids        integer[],
    rang_degrade           text,
    methode_approximation  text,
    ingredients            integer[],
    motif                  text,
    superseded_by          integer     REFERENCES public.framework_answers(id),
    created_at             timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT framework_answers_statut
        CHECK (statut IN ('repondu', 'approxime', 'sans_objet', 'non_fondable'))
);
-- La lecture chaude : la réponse COURANTE d'un (ticker, framework, version, question). Pas
-- d'UNIQUE : deux analystes peuvent répondre à la même question sans qu'aucune ligne ne supersède
-- l'autre (§3.4).
CREATE INDEX idx_framework_answers_courante
    ON public.framework_answers (ticker_id, framework, framework_version, question_id)
    WHERE superseded_by IS NULL;

-- Une dispense : « cette question n'a pas de sens pour CET émetteur », remplace
-- `DECLARED_NONBLOCKING_GAPS` (dict codé en dur, `curator.py:69`, NVDA/business_model.recurrence_pct
-- aujourd'hui). Clefée `(ticker_id, framework_id, framework_version, question_id)` + motif
-- obligatoire (spec §5.2) : SANS la version, une dispense survit à la question qu'elle dispensait
-- (écart V10 de l'audit) — c'est décrire un ÉMETTEUR (convention #31), donc ça va en base, jamais
-- dans une constante globale.
CREATE TABLE public.framework_dispenses (
    id                integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id         text        NOT NULL REFERENCES public.tickers(id),
    framework_id      text        NOT NULL,
    framework_version text        NOT NULL,
    question_id       text        NOT NULL,
    motif             text        NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT framework_dispenses_cle
        UNIQUE (ticker_id, framework_id, framework_version, question_id)
);

-- Le rôle applicatif lit et écrit ces tables. (La convention #15 — ALTER DEFAULT PRIVILEGES — couvre
-- déjà les tables créées par `admin` ; ce GRANT explicite est une ceinture par-dessus les bretelles.)
GRANT SELECT, INSERT, UPDATE, DELETE
    ON public.framework_answers, public.framework_dispenses
    TO portfolio_user;

COMMIT;
