-- Migration 042 — PERSISTANCE DE LA CARTE D'APPARIEMENT (chantier v3, lot 3 maillon 4bis étape 2b).
--
-- Grain : (ticker_id × framework_id × framework_version). Une seule carte par triplet : si la carte
-- doit être recalculée (nouveau dépôt), on l'ÉCRASE (UPSERT), ce n'est pas de la décision —
-- c'est la réponse correcte à un inventaire réel. Contrairement aux `framework_answers` (décisions
-- humaines, append-only) ou aux `knowledge_entries` (faits du corpus, append-only), une carte
-- d'appariement est une DÉRIVATION DÉTERMINISTE de l'inventaire + du plan : même entrées → même
-- sortie, donc pas d'historique à tenir.
--
-- REVÉRIFICATION À LA LECTURE (motif de #54)
-- -------------------------------------------
-- La colonne `dernier_depot_vu` est ce qui rend la revérification possible. Un `indisponible`
-- établi sur 269 concepts ne vaut rien contre un inventaire qui en compte 272 ; le point de
-- LECTURE doit s'en apercevoir (`feedback_controle_au_point_de_lecture`). La logique de
-- revérification vit dans le CODE (`appariement_persist.lire_carte`), pas ici : c'est une
-- comparaison de dates, pas un CHECK SQL.
--
-- POURQUOI JSONB ET PAS UNE TABLE NORMALISÉE
-- ------------------------------------------
-- Les items de la carte ont une structure variable (exact / approximation / indisponible n'ont pas
-- les mêmes champs), et leur contrat est déjà gardé par le schéma Pydantic (`appariement_schema.py`)
-- + le pont (`valider_pont_appariement`). Les dupliquer en colonnes serait un second détenteur —
-- d'accord avec le contrat aujourd'hui, divergent au premier champ ajouté (#46). Le JSONB ici est
-- la projection fidèle du contrat Python, pas une table indépendante.
--
-- ORDRE DU CHANTIER — l'agent dicte la table, comme en 039/041 : `AppariementCarte`,
-- `valider_pont_appariement` et `apparieur.apparier` sont écrits avant cette migration ;
-- la table est la projection de l'objet Python, jamais l'inverse.
--
-- CEs INVARIANTS SQL SE JUSTIFIENT PAR CE QU'ILS GARDENT, PAS PAR CE QU'ILS SONT
-- ---------------------------------------------------------------------------------
-- `dernier_depot_vu` NOT NULL : une carte sans date de dépôt ne peut pas se revérifier → elle se
--   relirait comme valide pour toujours (`feedback_controle_au_point_de_lecture`) ;
-- `items` JSONB NOT NULL : la carte doit décrire tous les ingrédients ; une carte vide ne peut pas
--   router le collecteur (on ne saurait pas si un ingrédient doit aller à EDGAR ou au web) ;
-- `framework_version` NOT NULL + dans la clef unique : une carte sans version survivrait à la
--   question qu'elle répondait — même mode de panne que #64 (`framework_answers`).

BEGIN;

CREATE TABLE IF NOT EXISTS public.appariement_cartes (
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id           text    NOT NULL REFERENCES tickers(id),
    framework_id        text    NOT NULL,
    framework_version   text    NOT NULL,

    -- La date du DÉPÔT le plus récent vu au moment du calcul (`apparieur.dernier_depot_vu`).
    -- C'est la borne de revérification : si le dépôt courant est plus récent, la carte est périmée.
    dernier_depot_vu    text    NOT NULL,

    -- La carte complète, telle que `AppariementCarte.model_dump()` la produit. Le contrat
    -- garantit la structure ; ici on ne persiste que la liste des items (l'en-tête ticker/framework/
    -- version est déjà dans les colonnes, pas besoin de le dupliquer dans le JSONB).
    items               jsonb   NOT NULL,

    created_at          timestamp with time zone NOT NULL DEFAULT now(),
    updated_at          timestamp with time zone NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.appariement_cartes IS
    'Carte d''appariement question→champ-EDGAR par (ticker × framework × version). '
    'Grain unique — une seule carte par triplet (UPSERT). Revérifiée à la lecture '
    'en comparant dernier_depot_vu au dépôt courant (motif de #54).';

COMMENT ON COLUMN public.appariement_cartes.dernier_depot_vu IS
    'Date ISO du dépôt le plus récent vu au moment du calcul (apparieur.dernier_depot_vu). '
    'La carte est invalidée si le dépôt courant est plus récent que cette date.';

COMMENT ON COLUMN public.appariement_cartes.items IS
    'JSON des AppariementItem — exactement ce que AppariementCarte.items produit. '
    'Le contrat Pydantic est le seul détenteur de la structure ; ici, pas de colonnes redondantes.';

-- Un seul appariement par (ticker × framework × version) — on ne garde pas l'historique (ce n'est
-- pas une décision, c'est une dérivation). Un nouveau dépôt = un UPSERT qui écrase l'ancienne carte.
CREATE UNIQUE INDEX IF NOT EXISTS uq_appariement_cartes
    ON public.appariement_cartes (ticker_id, framework_id, framework_version);

-- Index sur dernier_depot_vu pour les requêtes « quelle carte dois-je recalculer ? »
CREATE INDEX IF NOT EXISTS idx_appariement_cartes_depot
    ON public.appariement_cartes (ticker_id, dernier_depot_vu);

-- Trigger pour mettre à jour updated_at à chaque modification (même mécanique que les autres
-- tables qui ont un updated_at — pas de trigger déjà déclaré ici, donc on le crée).
CREATE OR REPLACE FUNCTION public.set_appariement_cartes_updated_at()
    RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_appariement_cartes_updated_at ON public.appariement_cartes;
CREATE TRIGGER trg_appariement_cartes_updated_at
    BEFORE UPDATE ON public.appariement_cartes
    FOR EACH ROW EXECUTE FUNCTION public.set_appariement_cartes_updated_at();

-- ── GARDE : items NON VIDE ────────────────────────────────────────────────────────────────────────
-- Une carte sans items ne peut pas router : on ne saurait pas si un ingrédient va à EDGAR ou au
-- web, et la suite croirait qu'il n'y a rien à collecter.
ALTER TABLE public.appariement_cartes
    ADD CONSTRAINT appariement_cartes_items_non_vide
    CHECK (jsonb_array_length(items) > 0);

-- ── GARDE : dernier_depot_vu a la forme d'une date ISO ───────────────────────────────────────────
-- Une chaîne qui n'est pas une date ferait échouer la comparaison dans le code de lecture sans
-- message d'erreur clair. Le CHECK garde la forme, pas le sens.
ALTER TABLE public.appariement_cartes
    ADD CONSTRAINT appariement_cartes_depot_format
    CHECK (dernier_depot_vu ~ '^\d{4}-\d{2}-\d{2}$');

COMMIT;
