-- Migration 048 — LE REGISTRE DU COMITÉ : acquitter / renvoyer, tracés (chantier v3, lot 6 maillon 3,
-- spec §8.2, audit A7 « overrides utilisateur tracés »).
--
-- ADDITIVE : une table NEUVE, aucune donnée existante touchée. Réversible par `DROP TABLE`.
--
-- ORDRE DU CHANTIER — l'AGENT dicte la table. Le contrat `contracts/comite_schema.py`
-- (`DecisionComite`) et l'agent `agents/v2/comite.py` (seul à écrire ici) sont écrits AVANT cette
-- migration : ces colonnes et ces CHECK sont la PROJECTION de `DecisionComite`, pas une conception
-- de schéma. Éprouvée en négatif AVANT application par `checks/negatif_048.sh`.
--
-- CE QUE FERAIT UN VRAI FONDS (arbitrages du comité, 2026-09-25)
--   n°1 — Quand le comité accepte une réponse faible, il écrit un PROCÈS-VERBAL COMPLET : qui, quand,
--         sur quelle version du dossier (framework + version + réponse), et une justification écrite
--         OBLIGATOIRE. ⟹ `auteur`, `decide_le`, `framework_version`, `answer_id`, `motif` non blanc.
--   n°2 — L'acceptation TOMBE dès qu'un fait important est publié après elle. ⟹ la validité N'EST PAS
--         une colonne (elle se recalcule à la lecture, #53) ; le PV note seulement le dernier fait
--         important CONNU au moment de la décision (`ancre_etat` + `fait_connu_*`), pour qu'on sache
--         plus tard ce qui est « nouveau ».
--   Un PV ne se réécrit pas. ⟹ APPEND-ONLY : le rôle applicatif n'a ni UPDATE ni DELETE, et un
--   trigger refuse toute réécriture même au propriétaire. Une décision nouvelle s'AJOUTE ; la plus
--   récente sur une question est la position du comité.

BEGIN;

CREATE TABLE public.comite_decisions (
    id                    integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id             text        NOT NULL REFERENCES public.tickers(id),
    framework_id          text        NOT NULL,
    framework_version     text        NOT NULL,
    question_id           text        NOT NULL,
    action                text        NOT NULL,
    -- La version du dossier que le comité a lue (obligatoire pour accepter, facultative pour renvoyer :
    -- on renvoie aussi une question qui n'a encore aucune réponse).
    answer_id             integer     REFERENCES public.framework_answers(id),
    -- Le mandat OUVERT par un renvoi (même canal que le manager, origine `comite`), et la recherche en
    -- cours que la décision a ARRÊTÉE (passée `abandonne`, jamais supprimée).
    mandat_id             integer     REFERENCES public.framework_mandates(id),
    mandat_remplace_id    integer     REFERENCES public.framework_mandates(id),
    auteur                text        NOT NULL,
    motif                 text        NOT NULL,
    -- Le dernier fait important connu à la décision — vocabulaire de `MaterialEventLookup.status`.
    ancre_etat            text        NOT NULL,
    fait_connu_publie_le  date,
    fait_connu_accession  text,
    fait_connu_resume     text,
    decide_le             timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT comite_decisions_action CHECK (action IN ('acquitter', 'renvoyer')),
    -- Projection de `DecisionComite._chaque_action_porte_sa_forme`.
    CONSTRAINT comite_decisions_forme CHECK (
        (action = 'acquitter' AND answer_id IS NOT NULL AND mandat_id IS NULL
                              AND ancre_etat <> 'unavailable')
        OR
        (action = 'renvoyer' AND mandat_id IS NOT NULL)
    ),
    -- Arbitrage n°1 : un PV signé et motivé. Un texte de blancs n'est pas un texte.
    CONSTRAINT comite_decisions_texte CHECK (btrim(auteur) <> '' AND btrim(motif) <> ''),
    -- #49 : `none` (on SAIT qu'il n'y a pas de fait) ≠ `unavailable` (on ne sait pas). Un fait est
    -- cité ssi l'ancre en a trouvé un.
    CONSTRAINT comite_decisions_ancre CHECK (
        ancre_etat IN ('found', 'none', 'unavailable')
        AND (ancre_etat = 'found') = (fait_connu_publie_le IS NOT NULL)
        AND (fait_connu_publie_le IS NULL) = (fait_connu_resume IS NULL)
        AND (fait_connu_publie_le IS NOT NULL OR fait_connu_accession IS NULL)
    )
);

-- La lecture chaude : le PV d'un émetteur pour une version des frameworks, le plus récent d'abord.
CREATE INDEX idx_comite_decisions_question
    ON public.comite_decisions (ticker_id, framework_version, framework_id, question_id, id DESC);

-- ── Append-only ────────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.comite_decisions_immuable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'comite_decisions est un procès-verbal : une décision ne se modifie ni ne se '
                  'supprime, une décision nouvelle s''ajoute (migration 048)';
END $$;

CREATE TRIGGER comite_decisions_immuable
    BEFORE UPDATE OR DELETE ON public.comite_decisions
    FOR EACH ROW EXECUTE FUNCTION public.comite_decisions_immuable();

-- Les privilèges par défaut (#15) donneraient TOUT au rôle applicatif : on retire la réécriture.
REVOKE ALL ON public.comite_decisions FROM portfolio_user;
GRANT SELECT, INSERT ON public.comite_decisions TO portfolio_user;

-- ── 048/K1 : le rôle applicatif ne peut QUE lire et ajouter ────────────────────────────────────
DO $$
BEGIN
  IF has_table_privilege('portfolio_user', 'public.comite_decisions', 'UPDATE')
     OR has_table_privilege('portfolio_user', 'public.comite_decisions', 'DELETE')
     OR has_table_privilege('portfolio_user', 'public.comite_decisions', 'TRUNCATE') THEN
    RAISE EXCEPTION '048/K1 : le rôle applicatif peut réécrire le procès-verbal du comité — un PV '
                    'réécrivable n''est pas une piste d''audit (A7)';
  END IF;
  IF NOT has_table_privilege('portfolio_user', 'public.comite_decisions', 'INSERT') THEN
    RAISE EXCEPTION '048/K1 : le rôle applicatif ne peut pas inscrire de décision';
  END IF;
END $$;

COMMENT ON TABLE public.comite_decisions IS
    'Procès-verbal du comité (migration 048) : une ligne par décision acquitter/renvoyer, append-only. '
    'La validité d''une acceptation se recalcule à la lecture (agents/v2/comite.py), jamais stockée.';

COMMIT;
