-- Migration 050 — LES NOTES FLASH : ce que la lecture d'un communiqué a conclu de sa portée (chantier v3,
-- lot 7, maillon 2 de la taxonomie des événements — `roadmap/V3/04-taxonomie-evenements.md` §10).
--
-- CE QUE FAIT UN VRAI FONDS
--   Le jour d'une publication, l'analyste qui couvre le titre la LIT et écrit une note flash : quels
--   points de la thèse sont touchés, en citant le passage. La note est écrite UNE fois : le communiqué
--   ne change pas. Ce qui change, c'est la grille de lecture (les méthodologies) — la portée de la note
--   se recalcule donc à chaque lecture contre le référentiel du jour (#53), jamais figée ici.
--
-- LE CAS (RVMD, 2026-08-26) : l'approbation FDA de RASONQUE est publiée en item 8.01 « autre événement
-- important » ; la forme ne dit pas la substance, le dépôt est `a_qualifier` et rouvre TOUTES les
-- questions (arbitrage Q3 : dans le doute on rouvre). Chez NVDA le 02/09, l'acquisition de Hugging Face
-- est annoncée en 8.01 aussi ; chez MSFT le 02/09, une présentation des nouveaux segments en 7.01 seul.
-- Sans lecture, les trois rouvrent tout ; lus, ils rouvrent ce qu'ils touchent.
--
-- FORME
--   · une ligne = une note, pour UN dépôt (accession) lu contre UNE version du catalogue ; la même
--     accession peut être relue sous une autre version du référentiel, jamais deux fois sous la même ;
--   · `types` = ce que le CODE a retenu (les `surprise_*` sont dérivés de la cause par le code, #57) ;
--     `elements` = la lecture du modèle, passages cités compris, telle que le pont l'a acceptée ;
--   · deux formes exclusives : lisible (≥ 1 type, jamais `a_qualifier`) ou illisible (`{a_qualifier}`
--     et un motif) — un dépôt lu-mais-indéterminable reste rouvert sur tout, et le motif dit pourquoi ;
--   · APPEND-ONLY (comme le PV du comité, 048) : l'application écrit et lit, ne réécrit jamais.
--
-- Éprouvée en négatif AVANT application par `checks/negatif_050.sh` (copie de `db_portfolio`).

BEGIN;

CREATE TABLE public.notes_flash (
    id                  integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id           text        NOT NULL REFERENCES public.tickers(id),
    cik                 integer     NOT NULL,
    accession           text        NOT NULL,
    form                text        NOT NULL,
    items               text[]      NOT NULL,
    event_date          date        NOT NULL,
    filing_date         date        NOT NULL,
    catalogue_version   text        NOT NULL,
    lisible             boolean     NOT NULL,
    types               text[]      NOT NULL,
    elements            jsonb       NOT NULL,
    motif               text,
    -- Ce que le modèle a eu sous les yeux : type SEC, nom et taille (lue / tronquée) de chaque document.
    documents           jsonb       NOT NULL,
    modele              text        NOT NULL,
    redigee_le          timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT notes_flash_une_lecture UNIQUE (accession, catalogue_version),
    CONSTRAINT notes_flash_texte CHECK (btrim(accession) <> '' AND btrim(modele) <> ''),
    CONSTRAINT notes_flash_documents CHECK (jsonb_typeof(documents) = 'array'
                                            AND jsonb_array_length(documents) >= 1),
    CONSTRAINT notes_flash_elements CHECK (jsonb_typeof(elements) = 'array'),
    -- Projection de `NoteFlashSortie._deux_formes`.
    CONSTRAINT notes_flash_forme CHECK (
        (lisible AND cardinality(types) >= 1 AND NOT ('a_qualifier' = ANY(types))
                 AND jsonb_array_length(elements) >= 1 AND motif IS NULL)
        OR
        (NOT lisible AND types = ARRAY['a_qualifier']::text[]
                     AND jsonb_array_length(elements) = 0 AND btrim(coalesce(motif, '')) <> '')
    )
);

CREATE INDEX notes_flash_cik ON public.notes_flash (cik);

CREATE OR REPLACE FUNCTION public.notes_flash_immuable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'notes_flash : une note flash ne se réécrit ni ne se supprime — un dépôt ne change '
                  'pas ; une relecture se fait sous une autre version du catalogue (migration 050)';
END $$;

CREATE TRIGGER notes_flash_immuable
    BEFORE UPDATE OR DELETE ON public.notes_flash
    FOR EACH ROW EXECUTE FUNCTION public.notes_flash_immuable();

REVOKE ALL ON public.notes_flash FROM portfolio_user;
GRANT SELECT, INSERT ON public.notes_flash TO portfolio_user;

-- ── 050/K1 : le rôle applicatif écrit et lit, sans jamais réécrire ────────────────────────────────
DO $$
BEGIN
  IF NOT has_table_privilege('portfolio_user', 'public.notes_flash', 'INSERT')
     OR NOT has_table_privilege('portfolio_user', 'public.notes_flash', 'SELECT') THEN
    RAISE EXCEPTION '050/K1 : le rôle applicatif ne peut pas écrire ou lire les notes flash';
  END IF;
  IF has_table_privilege('portfolio_user', 'public.notes_flash', 'UPDATE')
     OR has_table_privilege('portfolio_user', 'public.notes_flash', 'DELETE')
     OR has_table_privilege('portfolio_user', 'public.notes_flash', 'TRUNCATE') THEN
    RAISE EXCEPTION '050/K1 : le rôle applicatif peut réécrire une note flash — elle est immuable';
  END IF;
END $$;

COMMIT;
