-- Migration 051 — LE MODÈLE DE VALORISATION : versions proposées et procès-verbal de signature
-- (chantier v3, roadmap 05 capacité 4 bis, conventions #96/#97/#98).
--
-- ADDITIVE : deux tables NEUVES, aucune donnée existante touchée. Réversible par `DROP TABLE`.
--
-- ORDRE DU CHANTIER — l'AGENT dicte la table. Le contrat `contracts/signature_modele_schema.py`
-- (`VersionModele`, `DecisionModele`) et le module `valorisation/signature.py` (seul à écrire ici)
-- sont écrits AVANT cette migration : ces colonnes et ces CHECK en sont la PROJECTION. Éprouvée en
-- négatif AVANT application par `checks/negatif_051.sh`.
--
-- CE QUE FERAIT UN VRAI FONDS
--   L'analyste PROPOSE un modèle propre à l'entreprise ; le comité le SIGNE ou l'ÉCARTE, motif écrit,
--   et le PV garde la fourchette qu'il avait sous les yeux. Rien ne se réécrit : une révision est une
--   version NOUVELLE, une décision nouvelle s'AJOUTE. ⟹ deux registres APPEND-ONLY (le rôle applicatif
--   n'a ni UPDATE ni DELETE, un trigger refuse même au propriétaire), une décision au plus par version.

BEGIN;

CREATE TABLE public.modeles_valorisation (
    id              integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_id       text        NOT NULL REFERENCES public.tickers(id),
    version         integer     NOT NULL,
    schema_version  text        NOT NULL,
    auteur          text        NOT NULL,
    -- Le `ModeleValorisation` ENTIER (méthodologie, segments, tableau, forme, mécanique) : c'est ce
    -- que le comité signe, pas une projection en colonnes qui pourrait diverger du contrat.
    contenu         jsonb       NOT NULL,
    propose_le      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT modeles_valorisation_unique UNIQUE (ticker_id, version),
    CONSTRAINT modeles_valorisation_version CHECK (version >= 1),
    CONSTRAINT modeles_valorisation_auteur CHECK (btrim(auteur) <> ''),
    -- La ligne et son contenu disent la même chose : un modèle de NVDA rangé sous RVMD, ou une v2
    -- rangée en v3, serait signé pour ce qu'il n'est pas.
    CONSTRAINT modeles_valorisation_contenu CHECK (
        jsonb_typeof(contenu) = 'object'
        AND contenu->>'ticker_id' = ticker_id
        AND contenu->>'version' = version::text
        AND contenu->>'schema_version' = schema_version
    )
);

CREATE TABLE public.modeles_valorisation_decisions (
    id                  integer     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modele_id           integer     NOT NULL REFERENCES public.modeles_valorisation(id),
    action              text        NOT NULL,
    auteur              text        NOT NULL,
    motif               text        NOT NULL,
    -- La fourchette SIGNÉE, par action : ce que le comité avait sous les yeux.
    fourchette_bas      double precision,
    fourchette_central  double precision,
    fourchette_haut     double precision,
    -- Arbre d'événements : id → [valeur en échec, valeur en succès].
    par_evenement       jsonb,
    decide_le           timestamptz NOT NULL DEFAULT now(),

    -- Une version se décide UNE fois : signée ou écartée, jamais les deux, jamais deux fois.
    CONSTRAINT modeles_valorisation_decisions_unique UNIQUE (modele_id),
    CONSTRAINT modeles_valorisation_decisions_action CHECK (action IN ('signer', 'ecarter')),
    CONSTRAINT modeles_valorisation_decisions_texte CHECK (btrim(auteur) <> '' AND btrim(motif) <> ''),
    -- Projection de `DecisionModele._signer_porte_sa_fourchette` et de `Fourchette._ordonnee`.
    CONSTRAINT modeles_valorisation_decisions_forme CHECK (
        (action = 'signer' AND fourchette_bas IS NOT NULL AND fourchette_central IS NOT NULL
                           AND fourchette_haut IS NOT NULL
                           AND fourchette_bas <= fourchette_central
                           AND fourchette_central <= fourchette_haut)
        OR
        (action = 'ecarter' AND fourchette_bas IS NULL AND fourchette_central IS NULL
                            AND fourchette_haut IS NULL AND par_evenement IS NULL)
    )
);

CREATE INDEX idx_modeles_valorisation_decisions_modele
    ON public.modeles_valorisation_decisions (modele_id);

-- ── Append-only ────────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.modeles_valorisation_immuable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION '% est un registre : une version proposée ou une décision du comité ne se modifie '
                  'ni ne se supprime, une ligne nouvelle s''ajoute (migration 051)', TG_TABLE_NAME;
END $$;

CREATE TRIGGER modeles_valorisation_immuable
    BEFORE UPDATE OR DELETE ON public.modeles_valorisation
    FOR EACH ROW EXECUTE FUNCTION public.modeles_valorisation_immuable();
CREATE TRIGGER modeles_valorisation_decisions_immuable
    BEFORE UPDATE OR DELETE ON public.modeles_valorisation_decisions
    FOR EACH ROW EXECUTE FUNCTION public.modeles_valorisation_immuable();

-- Les privilèges par défaut (#15) donneraient TOUT au rôle applicatif : on retire la réécriture.
REVOKE ALL ON public.modeles_valorisation FROM portfolio_user;
REVOKE ALL ON public.modeles_valorisation_decisions FROM portfolio_user;
GRANT SELECT, INSERT ON public.modeles_valorisation TO portfolio_user;
GRANT SELECT, INSERT ON public.modeles_valorisation_decisions TO portfolio_user;

-- ── 051/K1 : le rôle applicatif ne peut QUE lire et ajouter, sur les DEUX registres ─────────────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['public.modeles_valorisation', 'public.modeles_valorisation_decisions'] LOOP
    IF has_table_privilege('portfolio_user', t, 'UPDATE')
       OR has_table_privilege('portfolio_user', t, 'DELETE')
       OR has_table_privilege('portfolio_user', t, 'TRUNCATE') THEN
      RAISE EXCEPTION '051/K1 : le rôle applicatif peut réécrire % — un registre réécrivable n''est '
                      'pas une piste d''audit (A7)', t;
    END IF;
    IF NOT has_table_privilege('portfolio_user', t, 'INSERT') THEN
      RAISE EXCEPTION '051/K1 : le rôle applicatif ne peut pas inscrire dans %', t;
    END IF;
  END LOOP;
END $$;

COMMENT ON TABLE public.modeles_valorisation IS
    'Versions proposées du modèle de valorisation d''un titre (migration 051), append-only. Écrit '
    'seulement par valorisation/signature.py.';
COMMENT ON TABLE public.modeles_valorisation_decisions IS
    'Procès-verbal de signature du modèle de valorisation (migration 051) : une décision signer/ecarter '
    'par version, append-only, la fourchette signée au PV. L''état du modèle se recalcule à la lecture.';

COMMIT;
