"""Fixture de SATISFIABILITÉ pour `tools/acceptation_frameworks.py` — émet du SQL, n'exécute rien.

POURQUOI CE FICHIER, ET POURQUOI IL N'EST PAS UNE MIGRATION
------------------------------------------------------------
`tools/acceptation_frameworks.py` est écrit AVANT la capacité et rougit sur ses 8 critères. Un
rouge seul ne prouve rien : il faut montrer que le test PEUT virer au vert (satisfiabilité), sinon
il rougirait aussi bien sur un critère impossible à satisfaire ; puis qu'une mutation par critère
le fait rougir (discrimination) — `feedback_acceptation_rouge_bidirectionnelle`. T1bis y est
particulièrement exposé : un critère qui exige qu'il MANQUE quelque chose est le plus facile à
satisfaire par accident.

Les tables `framework_answers` / `framework_mandates` appartiennent aux **lots 3-4**. Les créer ici
n'anticipe pas leur schéma de production : ce sont des tables de **rejeu**, posées sur une base
scratch jetable, dont la seule exigence est de porter les colonnes que l'acceptation LIT. C'est
pourquoi leur DDL est dérivée de `COLONNES_DENORMALISEES` — le détenteur du contrat (#46) — et non
retapée : le jour où le contrat renomme une colonne, la fixture suit, ou `_TYPES` lève en nommant
la colonne inconnue plutôt que de créer une table que l'acceptation lira `None`.

De même, les 33 ingrédients ESSENTIELS ne sont pas recopiés : ils sont lus dans
`app/frameworks/frameworks.yaml` par son chargeur. Un jumeau ici resterait vert le jour où le
référentiel s'enrichit — c'est exactement ce que T1 doit voir.

⚠️ LA FIXTURE NE FABRIQUE AUCUNE ENTRY (`feedback_fixture_copiee_du_reel`). Les liens de couverture
pointent des entries RÉELLES par sous-requête (`ORDER BY id LIMIT 1`), jamais un id en dur : une
fixture plus favorable que la production est un test aveugle au vert, et une fixture d'entries
fabriquées a déjà servi 12 jours de « corpus réel » sur ce projet.

Usage (dans l'image backend, pydantic v2) :

    python checks/_seed_acceptation_frameworks.py corpus > /tmp/corpus.sql   # ré-alimente public
    python checks/_seed_acceptation_frameworks.py         > /tmp/seed.sql    # la fixture
"""
from __future__ import annotations

import sys

from app.agents.v2.frameworks import load_frameworks
from app.contracts.framework_answer_schema import COLONNES_DENORMALISEES
from app.db.migrations._gen_036 import SUBSTITUTIONS_ENTRY_TYPE

TICKERS = ("NVDA", "MSFT", "RVMD")

# Le type SQL de chaque colonne dénormalisée. Clef = nom de COLONNE (les clefs de
# `COLONNES_DENORMALISEES`), pas le chemin de contrat. Une colonne ajoutée au contrat sans type ici
# fait LEVER : mieux qu'une table silencieusement incomplète, que l'acceptation lirait `None`.
_TYPES: dict[str, str] = {
    "framework":             "text NOT NULL",
    "question_id":           "text NOT NULL",
    "ticker_id":             "text NOT NULL",
    "analyste":              "text NOT NULL",
    "statut":                "text NOT NULL",
    "cited_entry_ids":       "integer[]",
    "rang_degrade":          "text",
    "methode_approximation": "text",
    "ingredients":           "integer[]",
    "motif":                 "text",
}


def _ddl_answers() -> str:
    inconnues = sorted(set(COLONNES_DENORMALISEES) - set(_TYPES))
    if inconnues:
        raise SystemExit(
            f"`_TYPES` ne connaît pas {inconnues} : le contrat a gagné des colonnes dénormalisées "
            f"et la fixture les créerait absentes. L'acceptation les lirait `None`, donc T3/T4 "
            f"rougiraient pour la mauvaise raison. Compléter `_TYPES`.")
    cols = ",\n    ".join(f"{c:<22} {_TYPES[c]}" for c in COLONNES_DENORMALISEES)
    return f"CREATE TABLE public.framework_answers (\n    id integer GENERATED BY DEFAULT AS " \
           f"IDENTITY PRIMARY KEY,\n    {cols}\n);"


def _recopie(table: str, *, sauf: str = "", ajout_cols: str = "", ajout_sel: str = "") -> str:
    """Un bloc `DO` qui recopie `archive_v2.<table>` dans `public.<table>`.

    La liste de colonnes est l'INTERSECTION des deux schémas, lue dans `information_schema` plutôt
    qu'écrite : la 036 retire 8 colonnes à `knowledge_entries`, et une liste retapée redeviendrait
    fausse à la migration suivante. `sauf` / `ajout_*` servent l'unique colonne qui ne se recopie
    pas telle quelle — `entry_type`, dont la 036 ferme le vocabulaire.
    """
    exclusion = f"\n     AND p.column_name <> '{sauf}'" if sauf else ""
    return f"""DO $$
DECLARE cols text;
BEGIN
  SELECT string_agg(format('%I', p.column_name), ', ' ORDER BY p.ordinal_position) INTO cols
    FROM information_schema.columns p
    JOIN information_schema.columns a
      ON a.table_schema = 'archive_v2' AND a.table_name = p.table_name
     AND a.column_name = p.column_name
   WHERE p.table_schema = 'public' AND p.table_name = '{table}'{exclusion};
  EXECUTE format(
    'INSERT INTO public.{table} (%s{ajout_cols}) '
    'SELECT %s{ajout_sel} '
    'FROM archive_v2.{table}', cols, cols);
END $$;
SELECT setval('public.{table}_id_seq', (SELECT max(id) + 1000 FROM public.{table}));"""


def corpus() -> int:
    """Ré-alimente `public.knowledge_entries` depuis `archive_v2`, sur la base scratch UNIQUEMENT.

    La 036 archive et recrée VIDE : sur la scratch, un test qui tournerait tout de suite après
    serait vrai sur zéro entry. En production ce trou se comble en **rejouant les producteurs
    déterministes** (planchers 50 et 13), jamais par une recopie — le corpus doit être ce que le
    code d'aujourd'hui produit. Ici c'est l'inverse qu'on veut : la fixture doit être le corpus
    RÉEL, celui sur lequel l'acceptation se jouera (`feedback_fixture_copiee_du_reel`).

    ⚠️ `knowledge_documents` se recopie AVANT : la 036 la recrée vide elle aussi, et chaque entry
    porte un `document_id` qui la référence. Ne pas la recopier obligerait à annuler le
    `document_id` — une scratch plus favorable que la production, donc un test aveugle au vert.
    """
    # ⚠️ Apostrophes DOUBLÉES : le `CASE` est interpolé dans un littéral SQL passé à `format()`.
    # Des quotes simples y refermeraient la chaîne — et `psql` échouerait sur une syntaxe qui a
    # l'air juste à la lecture.
    cas = " ".join(f"WHEN ''{av}'' THEN ''{ap}''"
                   for av, ap in sorted(SUBSTITUTIONS_ENTRY_TYPE.items()))
    print("\n".join([
        "BEGIN;",
        _recopie("knowledge_documents"),
        _recopie("knowledge_entries", sauf="entry_type",
                 ajout_cols=", entry_type",
                 ajout_sel=f", CASE entry_type {cas} ELSE entry_type END"),
        "DO $$ DECLARE n integer; BEGIN",
        "  SELECT count(*) INTO n FROM public.knowledge_entries;",
        "  IF n = 0 THEN RAISE EXCEPTION "
        "'corpus scratch VIDE — tout critère serait vrai sur zéro ligne';",
        "  END IF;",
        "END $$;",
        "COMMIT;",
    ]))
    return 0


def main() -> int:
    fichier = load_frameworks()
    version = fichier.schema_version

    # Les essentiels, lus chez leur détenteur. `(framework_id, question_id, ingredient_id)`.
    essentiels = [(f.id, q.id, ing.id)
                  for f in fichier.frameworks
                  for q in f.questions
                  for ing in q.ingredients_requis if ing.essentiel]
    if not essentiels:
        raise SystemExit("aucun ingrédient essentiel : la fixture rendrait T1 vert sur zéro ligne")

    out: list[str] = [
        "-- Fixture de satisfiabilité — générée par checks/_seed_acceptation_frameworks.py.",
        f"-- {len(essentiels)} ingrédients essentiels × {len(TICKERS)} tickers, "
        f"référentiel {version}.",
        "BEGIN;",
        _ddl_answers(),
        # `framework_mandates` n'est pas dénormalisée par le contrat du lot 1 : ses colonnes sont
        # celles que l'acceptation lit (`_mandate_ouvert`, T8). `ingredient_id` est load-bearing —
        # « un mandat sur la question » ne ferme rien si on ignore lequel il va chercher.
        "CREATE TABLE public.framework_mandates (",
        "    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,",
        "    framework_id   text NOT NULL,",
        "    question_id    text NOT NULL,",
        "    ingredient_id  text NOT NULL,",
        "    ticker_id      text NOT NULL,",
        "    statut         text NOT NULL,",
        "    consomme_at    timestamptz,",
        "    statut_avant   text,",
        "    statut_apres   text",
        ");",
    ]

    # ── Les mandats : TOUS les essentiels sont réclamés ──────────────────────────────────────
    # C'est la seule configuration qui rende T1 vert sans qu'aucune couverture n'existe — donc
    # celle qui montre que T1 sait compter « servi OU mandaté », et pas seulement « servi ».
    lignes = ",\n".join(
        f"  ('{fid}', '{qid}', '{ing}', '{t}', 'ouvert')"
        for t in TICKERS for fid, qid, ing in essentiels)
    out += ["INSERT INTO public.framework_mandates "
            "(framework_id, question_id, ingredient_id, ticker_id, statut) VALUES",
            lignes + ";"]

    # ── Les réponses ──────────────────────────────────────────────────────────────────────────
    # Deux `repondu` (pour que T2 ait de la matière : « 0 auto-fondée » sur zéro ligne est le 1ᵉʳ
    # faux vert) et un `sans_objet` motivé, qui exerce le chemin où T1 RETIRE une question du
    # périmètre — c'est le cas RVMD/`qf_1` de T4, et il ne doit pas compter comme un trou.
    out += [
        "INSERT INTO public.framework_answers "
        "(framework, question_id, ticker_id, analyste, statut, motif) VALUES",
        "  ('qualite_financiere', 'qf_2', 'NVDA', 'fixture', 'repondu', NULL),",
        "  ('qualite_financiere', 'qf_7', 'RVMD', 'fixture', 'repondu', NULL),",
        "  ('qualite_financiere', 'qf_1', 'RVMD', 'fixture', 'sans_objet', "
        "'aucun chiffre d''affaires : le rendement du capital n''a pas d''objet');",
    ]

    # ── La couverture : des entries RÉELLES, désignées par sous-requête ────────────────────────
    # `fact_financial` et non n'importe quoi : T2 exige une source PRIMAIRE, et servir la question
    # par une `agent_synthesis` serait déjà la mutation M4.
    def sert(ticker: str, qid: str, ing: str) -> str:
        return (f"INSERT INTO public.question_coverage "
                f"(framework_id, framework_version, question_id, ingredient_id, entry_id)\n"
                f"SELECT 'qualite_financiere', '{version}', '{qid}', '{ing}', e.id\n"
                f"  FROM public.knowledge_entries e\n"
                f" WHERE e.ticker_id = '{ticker}' AND e.superseded_by IS NULL\n"
                f"   AND e.entry_type = 'fact_financial'\n"
                f" ORDER BY e.id LIMIT 1;")

    out += [sert("NVDA", "qf_2", "resultat_net"),
            sert("RVMD", "qf_7", "tresorerie_disponible")]

    # Une fixture qui n'aurait servi personne rendrait T2 rouge sans qu'on sache si c'est le
    # critère ou la fixture : la garde le dit, en SQL, dans la transaction.
    out += [
        "DO $$ DECLARE n integer; BEGIN",
        "  SELECT count(*) INTO n FROM public.question_coverage;",
        "  IF n <> 2 THEN RAISE EXCEPTION "
        "'fixture : % lien(s) de couverture au lieu de 2 — le corpus scratch ne porte pas les "
        "entries attendues, T2 rougirait sur la fixture et non sur le critère', n; END IF;",
        "END $$;",
        "COMMIT;",
    ]

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(corpus() if sys.argv[1:2] == ["corpus"] else main())
